### PR TITLE
Added POD documentation for which version each feature appeared/changed in

### PR DESCRIPTION
**Pull request by BrianMowrey**
[RT#101518](https://rt.cpan.org/Public/Bug/Display.html?id=101518)

### CODE REVIEW

**Comment by dagolden** [comment]
Thanks!  There's some trailing white space and a couple typos ("vailable"), so if you could please correct that and push the fix, I'll merge it in.

**Comment by BrianMowrey** [comment]
Whoops, sorry about, I'd say something about not committing right before bed, but that's the only time I get to work on anything.  I've fixed the typo's/whitespace and squashed it back in to 1 commit.

**Comment by dagolden** [comment]
You still had trailing whitespace, but I squashed it.

Depending on your editor, you can get it to show it to you as you work. For
example, in vim, I have this in my .vimrc:

    set lcs=trail:⋅

Thanks for the research and patch.  It will be in the next release of
File::Temp whenever that happens.

David


On Wed, Feb 11, 2015 at 1:47 AM, BrianMowrey <notifications@github.com>
wrote:

> Whoops, sorry about, I'd say something about not committing right before
> bed, but that's the only time I get to work on anything. I've fixed the
> typo's/whitespace and squashed it back in to 1 commit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Perl-Toolchain-Gang/File-Temp/pull/8#issuecomment-73840209>
> .
>



-- 
David Golden <dagolden@cpan.org> Twitter/IRC: @xdg

**Comment by karenetheridge** [comment]
This was released in 0.2305-TRIAL today; thank you!

**Pull request closed without merging**
